// <auto-generated />
using System;
using DataProcessor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataProcessor.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251112120000_AddSettlementUploads")]
    partial class AddSettlementUploads : Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataProcessor.Data.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.ProcessedReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ProcessedReports");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.SettlementOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AmazonOrderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MarketplaceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MerchantFulfillmentId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MerchantOrderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PostedMonth")
                        .HasColumnType("int");

                    b.Property<int?>("PostedYear")
                        .HasColumnType("int");

                    b.Property<Guid>("SettlementUploadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ShipmentId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SettlementUploadId");

                    b.ToTable("SettlementOrders");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.SettlementOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AmazonOrderItemCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FeeComponents")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("FeeTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PriceComponents")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SettlementOrderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SettlementOrderId");

                    b.ToTable("SettlementOrderItems");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.SettlementUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime?>("DepositDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PeriodMonth")
                        .HasColumnType("int");

                    b.Property<int?>("PeriodYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SettlementId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserCnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SettlementUploads");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TrialExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("DataProcessor.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.ProcessedReport", b =>
                {
                    b.HasOne("DataProcessor.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("DataProcessor.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.SettlementOrder", b =>
                {
                    b.HasOne("DataProcessor.Data.Entities.SettlementUpload", "SettlementUpload")
                        .WithMany("Orders")
                        .HasForeignKey("SettlementUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SettlementUpload");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.SettlementOrderItem", b =>
                {
                    b.HasOne("DataProcessor.Data.Entities.SettlementOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("SettlementOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.SettlementUpload", b =>
                {
                    b.HasOne("DataProcessor.Data.Entities.User", "User")
                        .WithMany("SettlementUploads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.Subscription", b =>
                {
                    b.HasOne("DataProcessor.Data.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.SettlementOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.SettlementUpload", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DataProcessor.Data.Entities.User", b =>
                {
                    b.Navigation("SettlementUploads");
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
